### ISSUE TITLE
Consider licensing this under Apache or MIT?

### ISSUE THREAD

**Issue by saarw** [rolag/lockfreehashmap-rs#1]
This looks like an interesting library for some of my problems, but as most Rust programs are statically linked it is hard to use LGPL commercially. Would you consider changing this to MIT or Apache license?

**Comment by rolag** [comment]
As far as I'm aware, libraries can be compiled dynamically in rust using `#[crate_type = "dylib"]` (among other methods) so my current point of view is to keep the license as it is, sorry.

**Comment by saarw** [comment]
Ok, np, sometimes people just slap a license on it without giving a thought to the conditions. Figured I'd ask before porting my own lockfree hashmap from the same Java sources, but turns out a regular locking concurrent hashmap seems to do the trick for me, so won't bother. Thanks for the reply.
