### ISSUE TITLE
Iterator over key/value set

### ISSUE THREAD

**Issue by 0xpr03** [rolag/lockfreehashmap-rs#2]
Hello,
I'm not seeing any function for iterating over the set of keys. ([Keys](https://doc.rust-lang.org/std/collections/struct.HashMap.html?search=#method.keys ))
This is kind of a requirement for removing elements on a time based cache.
Is this a planned feature or not possible due to the implementation ?

**Comment by rolag** [comment]
This was a side project of mine and I don't have any plans to develop it much further currently. With that said, implementing a key iterator is rather easy so I'll push a fix soonish.

**Comment by 0xpr03** [comment]
I'd recommend marking this project as archived if you don't intend to support it any further.
