### ISSUE TITLE
Depends on old broken version of crossbeam-epoch

### ISSUE THREAD

**Issue by RalfJung** [rolag/lockfreehashmap-rs#5]
The version of crossbeam-epoch this depends on is very old and has many known problems. It might stop working with future compiler versions (see https://github.com/rust-lang/rust/pull/71274). Would be great if you could update to at least version 0.7.2. :)

**Comment by rolag** [comment]
That would require rewriting a lot of code to work with a new version of crossbeam. Unfortunately, I do not have the time to maintain this so I will archive this project for now.
